In [42]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [43]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import hvplot.pandas  
import holoviews as hv 
import panel as pn

In [45]:
%%capture
hv.extension('bokeh')
pn.extension(comms="vscode")

In [46]:
df = pd.read_csv('WHO-COVID-19-global-data.csv')
df2 = pd.read_csv('cause_of_deaths.csv')
df3 = pd.read_csv('Infectious_Disease_cases2001-2014.csv')
df2.head()

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,2231,3932,451,3038,6001,6664,3027,5739,420,3816

In [34]:
df2.isnull().sum()

Country/Territory                             0
Code                                          0
Year                                          0
Meningitis                                    0
Alzheimer's Disease and Other Dementias       0
Parkinson's Disease                           0
Nutritional Deficiencies                      0
Malaria                                       0
Drowning                                      0
Interpersonal Violence                        0
Maternal Disorders                            0
HIV/AIDS                                      0
Drug Use Disorders                            0
Tuberculosis                                  0
Cardiovascular Diseases                       0
Lower Respiratory Infections                  0
Neonatal Disorders                            0
Alcohol Use Disorders                         0
Self-harm                                     0
Exposure to Forces of Nature                  0
Diarrheal Diseases                            0
Environmental Heat and Cold Exposure          0
Neoplasms                                     0
Conflict and Terrorism                        0
Diabetes Mellitus                             0
Chronic Kidney Disease                        0
Poisonings                                    0
Protein-Energy Malnutrition                   0
Road Injuries                                 0
Chronic Respiratory Diseases                  0
Cirrhosis and Other Chronic Liver Diseases    0
Digestive Diseases                            0
Fire, Heat, and Hot Substances                0
Acute Hepatitis                               0
dtype: int64

In [35]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6120 entries, 0 to 6119
Data columns (total 34 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country/Territory                           6120 non-null   object
 1   Code                                        6120 non-null   object
 2   Year                                        6120 non-null   int64
 3   Meningitis                                  6120 non-null   int64
 4   Alzheimer's Disease and Other Dementias     6120 non-null   int64
 5   Parkinson's Disease                         6120 non-null   int64
 6   Nutritional Deficiencies                    6120 non-null   int64
 7   Malaria                                     6120 non-null   int64
 8   Drowning                                    6120 non-null   int64
 9   Interpersonal Violence                      6120 non-null   int64
 10  Maternal Disorders                          6120 non-null   int64
 11  HIV/AIDS                                    6120 non-null   int64
 12  Drug Use Disorders                          6120 non-null   int64
 13  Tuberculosis                                6120 non-null   int64
 14  Cardiovascular Diseases                     6120 non-null   int64
 15  Lower Respiratory Infections                6120 non-null   int64
 16  Neonatal Disorders                          6120 non-null   int64
 17  Alcohol Use Disorders                       6120 non-null   int64
 18  Self-harm                                   6120 non-null   int64
 19  Exposure to Forces of Nature                6120 non-null   int64
 20  Diarrheal Diseases                          6120 non-null   int64
 21  Environmental Heat and Cold Exposure        6120 non-null   int64
 22  Neoplasms                                   6120 non-null   int64
 23  Conflict and Terrorism                      6120 non-null   int64
 24  Diabetes Mellitus                           6120 non-null   int64
 25  Chronic Kidney Disease                      6120 non-null   int64
 26  Poisonings                                  6120 non-null   int64
 27  Protein-Energy Malnutrition                 6120 non-null   int64
 28  Road Injuries                               6120 non-null   int64
 29  Chronic Respiratory Diseases                6120 non-null   int64
 30  Cirrhosis and Other Chronic Liver Diseases  6120 non-null   int64
 31  Digestive Diseases                          6120 non-null   int64
 32  Fire, Heat, and Hot Substances              6120 non-null   int64
 33  Acute Hepatitis                             6120 non-null   int64
dtypes: int64(32), object(2)
memory usage: 1.6+ MB

In [36]:
df2.describe()

,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,Maternal Disorders,HIV/AIDS,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
count,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,...,6120.000000,6120.000000,6120.000000,6120.000000,6120.000000,6.120000e+03,6120.000000,6120.000000,6120.000000,6120.000000
mean,2004.500000,1719.701307,4864.189379,1173.169118,2253.600000,4140.960131,1683.333170,2083.797222,1262.589216,5941.898529,...,5138.704575,4724.132680,425.013399,1965.994281,5930.795588,1.709237e+04,6124.072059,10725.267157,588.711438,618.429902
std,8.656149,6672.006930,18220.659072,4616.156238,10483.633601,18427.753137,8877.018366,6917.006075,6057.973183,21011.962487,...,16773.081040,16470.429969,2022.640521,8255.999063,24097.784291,1.051572e+05,20688.118580,37228.051096,2128.595120,4186.023497
min,1990.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,1997.000000,15.000000,90.000000,27.000000,9.000000,0.000000,34.000000,40.000000,5.000000,11.000000,...,236.000000,145.750000,6.000000,5.000000,174.750000,2.890000e+02,154.000000,284.000000,17.000000,2.000000
50%,2004.500000,109.000000,666.500000,164.000000,119.000000,0.000000,177.000000,265.000000,54.000000,136.000000,...,1087.000000,822.000000,52.500000,92.000000,966.500000,1.689000e+03,1210.000000,2185.000000,126.000000,15.000000
75%,2012.000000,847.250000,2456.250000,609.250000,1167.250000,393.000000,698.000000,877.000000,734.000000,1879.000000,...,2954.000000,2922.500000,254.000000,1042.500000,3435.250000,5.249750e+03,3547.250000,6080.000000,450.000000,160.000000
max,2019.000000,98358.000000,320715.000000,76990.000000,268223.000000,280604.000000,153773.000000,69640.000000,107929.000000,305491.000000,...,273089.000000,222922.000000,30883.000000,202241.000000,329237.000000,1.366039e+06,270037.000000,464914.000000,25876.000000,64305.000000

In [63]:
df2['Country/Territory'].unique()
list_of_countries = []
for item in df2['Country/Territory'].unique():
    list_of_countries.append(item)
print(list_of_countries)

['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea', 'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe']

In [39]:
pd.set_option('display.max_rows', 180)
(df2
    .filter(['Country/Territory'])
    .drop_duplicates()
)

     Country/Territory
0          Afghanistan
30             Albania
60             Algeria
90      American Samoa
120            Andorra
...                ...
5970         Venezuela
6000           Vietnam
6030             Yemen
6060            Zambia
6090          Zimbabwe

[204 rows x 1 columns]

In [61]:
label_selector = pn.widgets.Select(   # create a Select widget
    name='Label',                     # name of the widget
    options=list_of_countries,    # options for users to select from
)
x_slider = pn.widgets.FloatSlider( # create a FloatSlider
    name='Min x',                  # name of the widget
    start=0.0,                     # lower bound of the slider
    end=1.0,                       # upper bound of the slider
    step=0.01,                     # step value
    value=0.0                      # default value of the slider
)
y_slider = pn.widgets.FloatSlider( # create a FloatSlider
    name='Min Y',                  # name of the widget
    start=0.0,                     # lower bound of the slider
    end=1.0,                       # upper bound of the slider
    step=0.01,                     # step value
    value=0.0                      # default value of the slider
)

pn.Column(
    label_selector,
    x_slider,
    y_slider,
)

BokehModel(combine_events=True, render_bundle={'docs_json': {'8d80c998-b98e-42f0-b1ad-9fcc4b328c40': {'versionâ€¦

In [62]:
def plot_my_data(label, min_x, min_y):
    # uses `data` from the global scope!
    mask = (df2['Country/Territory'] == label) & (df2.Malaria >= min_x) & (df2.Year >= min_y)
    return df2[mask].hvplot.scatter(
        x='Malaria',
        y='Year',
        color='Country/Territory'
    ).opts(
        title='Random Data',
        show_grid=True,
        framewise=True
    )

label_selector = pn.widgets.Select(   # create a Select widget
    name='Label',                     # name of the widget
    options=list_of_countries,    # options for users to select from
)
x_slider = pn.widgets.FloatSlider( # create a FloatSlider
    name='Min X',                  # name of the widget
    start=0.0,                     # lower bound of the slider
    end=1.0,                       # upper bound of the slider
    step=0.01,                     # step value
    value=0.0                      # default value of the slider
)
y_slider = pn.widgets.FloatSlider( # create a FloatSlider
    name='Min Y',                  # name of the widget
    start=0.0,                     # lower bound of the slider
    end=1.0,                       # upper bound of the slider
    step=0.01,                     # step value
    value=0.0                      # default value of the slider
)


# we use `pn.interact` to connect our widgets to our plotting function
# every argument in our function gets mapped to a widget using keyword-arguments
interaction = pn.interact(plot_my_data, label=label_selector, min_x=x_slider, min_y=y_slider)
interaction

BokehModel(combine_events=True, render_bundle={'docs_json': {'b5e1b303-c095-4d91-917c-6bd9c512dfda': {'versionâ€¦